# Generated by Django 4.1.2 on 2022-11-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
