# Generated by Django 4.1.2 on 2022-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_shippingaddress_customer_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
