# Generated by Django 4.1.2 on 2022-11-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_products_image1_products_image2_products_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
