# Generated by Django 4.1.2 on 2022-11-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='guestUser',
        ),
    ]
