# Generated by Django 4.1.2 on 2022-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_offer_coupons_active_coupons_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer',
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
