# Generated by Django 4.1.2 on 2022-12-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_category_offer_remove_products_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
            preserve_default=False,
        ),
    ]
