# Generated by Django 4.1.2 on 2022-12-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_user_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
