# Generated by Django 4.1.2 on 2022-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
    ]
