# Generated by Django 4.1.2 on 2022-12-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
